-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(30 * A.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE LIKE '30%'
    AND A.CAR_TYPE IN ('세단', 'SUV')
    AND A.CAR_ID NOT IN (SELECT CAR_ID
                             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                             WHERE START_DATE <= '2022-11-30'
                                AND END_DATE >= '2022-11-01')
GROUP BY A.CAR_ID
HAVING FEE >= 500000
    AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC


# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
