-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE AS s
JOIN USER_INFO AS u
ON s.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;
