SELECT D.ROUTE AS ROUTE
    , CONCAT(ROUND(SUM(D.D_BETWEEN_DIST),1), 'km') AS TOTAL_DISTANCE
    , CONCAT(ROUND(AVG(D.D_BETWEEN_DIST),2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE D
GROUP BY D.ROUTE
ORDER BY ROUND(SUM(D.D_BETWEEN_DIST),1) DESC

# SELECT DISTINCT D.ROUTE AS ROUTE
#     , CONCAT(ROUND(SUM(D.D_BETWEEN_DIST) OVER (PARTITION BY D.ROUTE) , 1), 'km') AS TOTAL_DISTANCE
#     , CONCAT(ROUND(AVG(D.D_BETWEEN_DIST) OVER (PARTITION BY D.ROUTE) , 2), 'km') AS AVERAGE_DISTANCE
# FROM SUBWAY_DISTANCE D
# ORDER BY TOTAL_DISTANCE DESC