# SELECT DISTINCT COUNT(I.ID) OVER (PARTITION BY N.FISH_NAME) AS FISH_COUNT
#     , N.FISH_NAME AS FISH_NAME
# FROM FISH_INFO I, FISH_NAME_INFO N
# WHERE I.FISH_TYPE = N.FISH_TYPE
# ORDER BY FISH_COUNT DESC

SELECT COUNT(I.FISH_TYPE) AS FISH_COUNT
    , N.FISH_NAME AS FISH_NAME
FROM FISH_INFO I, FISH_NAME_INFO N
WHERE I.FISH_TYPE = N.FISH_TYPE
GROUP BY I.FISH_TYPE, N.FISH_NAME
ORDER BY FISH_COUNT DESC
