-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) AS YEAR, 
    MONTH(s.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT s.USER_ID) AS PUCHASED_USERS, 
    ROUND(COUNT(DISTINCT s.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS s
LEFT JOIN USER_INFO AS u
ON u.USER_ID = s.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
ORDER BY YEAR, MONTH;