WITH RECURSIVE RC AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM RC
    WHERE HOUR < 23
)
SELECT RC.HOUR
    , IFNULL(CNT.COUNT, 0) AS COUNT
FROM RC
LEFT OUTER JOIN (
    SELECT HOUR(DATETIME) AS HOUR
        , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY 1
    ORDER BY 1
 ) CNT
ON RC.HOUR = CNT.HOUR

