SELECT U.UPDATE_ID AS ITEM_ID, U.UPDATE_NAME AS ITEM_NAME, U.RARITY
    FROM ITEM_INFO I, 
    (SELECT T.ITEM_ID, P.ITEM_ID AS UPDATE_ID, I.ITEM_NAME AS UPDATE_NAME, I.RARITY
        FROM ITEM_TREE T, ITEM_TREE P, ITEM_INFO I
        WHERE T.ITEM_ID = P.PARENT_ITEM_ID
        AND P.ITEM_ID = I.ITEM_ID) U
    WHERE I.ITEM_ID = U.ITEM_ID
    AND I.RARITY = 'RARE'
    ORDER BY UPDATE_ID DESC;
    
    
# SELECT T.PARENT_ITEM_ID, I.ITEM_NAME, I.RARITY
#     FROM ITEM_INFO I, ITEM_TREE T
#     WHERE I.ITEM_ID = T.PARENT_ITEM_ID 
#     AND I.RARITY = 'RARE'

# SELECT T.ITEM_ID, P.ITEM_ID AS UPDATE_ID, I.ITEM_NAME AS UPDATE_NAME, I.RARITY
#     FROM ITEM_TREE T, ITEM_TREE P, ITEM_INFO I
#     WHERE T.ITEM_ID = P.PARENT_ITEM_ID
#     AND P.ITEM_ID = I.ITEM_ID