-- 코드를 입력하세요
SELECT MCDP_CD AS '진료과코드', COUNT (DISTINCT PT_NO) AS '5월예약건수'
FROM APPOINTMENT
WHERE APNT_YMD LIKE '2022-05%'
    # AND (APNT_CNCL_YN IS NULL OR APNT_CNCL_YN = 'N')
GROUP BY MCDP_CD
ORDER BY 2, 1

