SELECT I.ID AS ID
    , N.FISH_NAME AS FISH_NAME
    , I.LENGTH AS LENGTH
FROM FISH_INFO I, FISH_NAME_INFO N
    ,(SELECT I.ID AS ID
        , N.FISH_NAME AS FISH_NAME
        , ROW_NUMBER() OVER(PARTITION BY N.FISH_NAME ORDER BY I.LENGTH DESC) ranks
    FROM FISH_INFO I, FISH_NAME_INFO N
    WHERE I.FISH_TYPE = N.FISH_TYPE) R
WHERE I.FISH_TYPE = N.FISH_TYPE
AND I.ID = R.ID 
AND R.RANKS = 1
ORDER BY ID ASC;

# SELECT I.ID AS AD
#     , N.FISH_NAME AS FISH_NAME
#     , ROW_NUMBER() OVER(PARTITION BY N.FISH_NAME ORDER BY I.LENGTH DESC) ranks
# FROM FISH_INFO I, FISH_NAME_INFO N
# WHERE I.FISH_TYPE = N.FISH_TYPE