SELECT COUNT(*) AS FISH_COUNT
    , MAX(I.LEN) AS MAX_LENGTH
    , I.FISH_TYPE AS FISH_TYPE
FROM (
    SELECT *
        , IFNULL(LENGTH, 10) AS LEN
    FROM FISH_INFO
    ) I
GROUP BY I.FISH_TYPE
HAVING AVG(I.LEN) >= 33
ORDER BY FISH_TYPE ASC;



    